### ISSUE TITLE
Show current(/upcoming) run(s) on home screen

### ISSUE THREAD

**Issue by zoton2** [esamarathon/esa-mobile-app#1]
Would be useful to easily see what is going on. Doesn't have to be overly detailed and could link to the same thing the runs on the schedules link to.

**Comment by ChrisRu** [comment]
An early version of this has been added earlier in 3775ad9fe3836414146b1f420097f7663e12fa10

**Comment by olidotjpeg** [comment]
This is no longer in there after the new design in #10

**Comment by olidotjpeg** [comment]
This have been added to the current design.

![image](https://user-images.githubusercontent.com/1591885/71526152-bea74600-28d5-11ea-9ea1-7128f4ed927c.png)
