### ISSUE TITLE
Upgrade React Native to 0.60

### ISSUE THREAD

**Issue by ChrisRu** [esamarathon/esa-mobile-app#24]
Right now the app is on 0.59, but the next update 0.60 has better accessibility, AndroidX support and uses CocoaPods. https://facebook.github.io/react-native/blog/2019/07/03/version-60

**Comment by ChrisRu** [comment]
If you're gonna try to upgrade it, you will want to update all other dependencies as well, especially the `react-native-*` ones. 

You can use https://react-native-community.github.io/upgrade-helper/ to see the diffs for your upgrade and follow all these details.

While trying to run this upgrade I've had some issues with libraries not yet being able to support AndroidX.
- gradle needs to be updated to at least 5.1.1, otherwise it can't work with the new packages.
- Importing PackageList in Java didn't seem to work
- `react-native-firebase` has troubles with auto linking dependencies which causes Java builds to fail.
- `react-native-gesture-handler` encountered troubles with not being able to resolve the namespaces in MainActivity.java
- `react-native-linear-gradient` 2.5.5 accidentally included a .git folder which causes npm installs to fail.
- `jetifier` didn't seemt to fix dependency issues

**Comment by ChrisRu** [comment]
It might be a good idea to hold out on upgrading to next month so all the bugs regarding these native packages have been resolved

**Comment by olidotjpeg** [comment]
A version of the app running React Native 0.60 has been added to branch Reboot
